### ISSUE TITLE
[PLEASE RESPOND] How do i get the posts to load in the homepage (index) ?

### ISSUE THREAD

**Issue by Joseph10i** [Hidroxiuro/Hidroxiuro.github.io#3]
The posts don't load by default, I only see the loading.gif icon but the posts never load. PLEASE RESPOND

**Comment by Joseph10i** [comment]
Figured it out

**Comment by Hidroxiuro** [comment]
Hi. I took this project from someone else from github for a school project like 4 years ago.

The only reason why on github is cuz i needed somewhere to showcase it.

I really dont remeber how it works anymore lol

**Comment by Joseph10i** [comment]
yeah, no worries. I figured out why it wasn't loading.
